### PR TITLE
Avoid building linux-specific feature (BindToDevice) on other platforms

### PR DESCRIPTION
**Pull request by radeksimko**
https://github.com/FiloSottile/captive-browser/pull/12 introduced a linux-specific constant without constraining that logic to linux, so here's a PR which fixes that 😉 

Without this patch compilation fails on darwin (and other platforms except on linux):

```
$ go get -u github.com/FiloSottile/captive-browser
# github.com/FiloSottile/captive-browser
gopath/src/github.com/FiloSottile/captive-browser/main.go:96:12: undefined: syscall.BindToDevice
```

I have _not_ tested this on Linux beyond checking that `GOOS=linux go build .` produces a binary without any errors.

### CODE REVIEW

**Comment by FiloSottile** [comment]
Huh, I added the Travis-CI integration specifically to check that it was still building on macOS. I'm confused.

**Comment by FiloSottile** [comment]
Yeah, for some reason the GOOS env var was being ignored or overridden. See #15.

**Comment by FiloSottile** [comment]
Yeah, for some reason the GOOS env var was being ignored or overridden. See #15.

**Comment by FiloSottile** [comment]
You checked in a binary, please remove and rebase on top of the new Travis config.

**Comment by radeksimko** [comment]
> You checked in a binary

Doh! Sorry about that. It should be gone now. PTAL.

**Pull request merged**
