### PR TITLE
Support retrieval of DHCP DNS servers from systemd via DBus

### PR DESCRIPTION
**Pull request by chrissnell**
This PR adds support for pulling DHCP DNS servers from systemd via DBus.  Many distros (e.g. Arch Linux) use systemd-networkd in place of NetworkManager.  systemd-networkd does not make it easy to access the DHCP-provided nameservers from the command line.   This code makes calls to the system DBus to retrrieve the nameservers via the systemd-resolved API.

### CODE REVIEW

**Comment by chrissnell** [comment]
Hi,

Is there any interest in this PR?  If not, I plan on forking captive-browser and making a more systemd-specific flavor.

**Comment by FiloSottile** [comment]
Hi @chrissnell! Sorry for not replying sooner. I was fairly happy with the clear delegation line of using shell commands for this, which I guess is a way of saying that I enjoyed the UNIXness of it. 

But that's being an anti-systemd clichè, and I realize that.

How about this solution: we ship with captive-browser a command line tool that extracts DNS from DBus, you install it with `go get github.com/FiloSottile/captive-browser/...` and we make sure the shell command is passed the path of the `captive-browser` binary so it can easily call the other binary.

The advantage is that it might also be a useful thing on its own!

**Comment by chrissnell** [comment]
I'll be honest, I'm not interested in re-working this into a standalone binary.  I prefer to do as much as possible without shelling out.  I've been using my modified captive-browser for almost a month now and the DBus stuff works fantastically well and quick.  There's just no way to easily get at the nameservers w/o going through DBus so this is a pretty important  feature for me, personally.

 I don't think its presence creates that much confusion for the user and the binary is only a small amount larger.   If you don't want it in the core, that's fine, close the PR and I will maintain my own version for my own use.

**Comment by chrissnell** [comment]
OK, I reworked this as a separate command.  Does this work better for you?

**Comment by FiloSottile** [comment]
Thanks! I'll add it to the README.

**Pull request merged**
